insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 1232, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 780, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 1023, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 1295, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 226, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 295, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 809, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 255, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 1214, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 917, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 1122, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Pearl', 1101, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 1221, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 398, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 278, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 1216, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 813, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 844, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 935, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 312, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 355, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 942, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 210, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 438, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 770, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 690, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 567, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Pearl', 487, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 680, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 800, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 587, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Pearl', 852, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 752, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Pearl', 841, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 377, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 771, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 1101, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 1004, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Pearl', 951, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 622, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 638, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Pearl', 238, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 571, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 610, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 333, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 679, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 958, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Tama', 1007, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'DW', 1192, 0);
insert into instrument (type, brand, price, is_being_rented) values ('Drums', 'Yamaha Sonor', 1071, 0);
